app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/merxury/blocker/rule/Rule.kt
app/src/main/java/com/merxury/blocker/ui/component/ComponentActivity.kt
app/src/main/java/com/merxury/blocker/ui/component/ComponentPresenter.kt
app/src/main/java/com/merxury/blocker/ui/settings/SettingsActivity.kt
app/src/main/java/com/merxury/blocker/ui/settings/SettingsPresenter.kt
build.gradle
core/build.gradle
ifw-api/build.gradle
libkit/build.gradle
libkit/src/main/java/com/merxury/libkit/utils/FileUtils.kt
libkit/src/main/java/com/merxury/libkit/utils/ModernStorageUtils.kt

much problems on used path, user-manually guide, and code implementations are related. so new code needs be later.

temporarily uses requestLegacyStorage for Android 10

---

app-compose/src/main/java/com/merxury/blocker/ui/BlockerAppState.kt

Change-Id: I928f607981ad221d969781487b0c7e11d03c3a7b

Remove hide bottom bar logic and fix automation tests

---

app-compose/src/main/AndroidManifest.xml

Change-Id: I598f868a78a2dbf3e7c940b169d3e0733dc156bb

Add com.google.android.gms.permission.AD_ID permission

---

.github/workflows/Build.yaml
app-compose/build.gradle.kts

Change-Id: I59bd35f5ed673bfea7bcfd1131fbe14b27dd350c

Update CI to do the auto signing

---

.github/workflows/Build.yaml
.github/workflows/Release.yml

Change-Id: I5b76c44f413b6c0948865004024906933a52dca6

Optimize CI build script

---

core/ui/src/main/java/com/merxury/blocker/core/ui/bottomsheet/AppSortBottomSheet.kt
feature/appdetail/build.gradle.kts
feature/appdetail/src/main/java/com/merxury/blocker/feature/appdetail/AppDetailScreen.kt
feature/applist/build.gradle.kts
feature/applist/src/main/java/com/merxury/blocker/feature/applist/AppListScreen.kt
gradle/libs.versions.toml

Remove 3rd party bottom sheet library

---

app-compose/src/debug/res/drawable/ic_launcher_background.xml
app-compose/src/debug/res/drawable/ic_launcher_foreground.xml

Change-Id: I0ca020a15bd8b55a4fb46d413742fcf88ee1feaa

Add icon in debug mode

---

feature/search/src/main/java/com/merxury/blocker/feature/search/SearchScreen.kt

Resume to unselect mode when clicking system back button in selected mode

Fix back button on selected mode

---

core/ifw-api/src/main/java/com/merxury/core/ifw/IfwEntity.kt
core/ifw-api/src/test/java/com/merxury/core/ifw/IntentFirewallUnitTest.kt

Change-Id: I77e479e513955744fa8fe8f8f7450f5ea936cd2f

Use Set to store components to avoid duplicates

---

feature/search/src/main/java/com/merxury/blocker/feature/search/model/SearchViewModel.kt

Fix issue: doesn't update selected componentList when select/de-select all

Fix select component issues:

---

feature/search/src/main/java/com/merxury/blocker/feature/search/model/SearchViewModel.kt

Should not search when search keyword doesn't updated.

Fix issue: list will refresh when showing/hiding keyboard

---

core/designsystem/src/main/kotlin/com/merxury/blocker/core/designsystem/component/CollapsingTopAppBar.kt
core/designsystem/src/main/kotlin/com/merxury/blocker/core/designsystem/component/TextField.kt
core/designsystem/src/main/res/values/strings.xml
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailScreen.kt

1. Set the searchTextField to fill the remaining weight
2. Set the placeHolder text auto-size

Fix the more button will be covered in some small screen devices

---

feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/item/SwitchSettingItem.kt

Fix https://github.com/lihenggui/blocker/issues/364

Fix issue: Switch button will cover the text content

---

gradle/wrapper/gradle-wrapper.properties

Change-Id: I77e29cfcff663616efd8115bdb10f10bc41bc09e

Upgrade to Gradle v8.4

---

core/rule/src/main/AndroidManifest.xml
core/rule/src/main/kotlin/com/merxury/blocker/core/rule/work/RuleNotificationWorker.kt
sync/work/src/main/AndroidManifest.xml
sync/work/src/main/kotlin/com/merxury/blocker/sync/initializers/SyncWorkHelpers.kt

Change-Id: Ica0d263033c83cfb7d901e7ca84748183672b312

Add foreground service types to avoid crashing on Android 14 devices.

---

feature/ruledetail/src/androidTest/kotlin/com/merxury/blocker/feature/ruledetail/RuleDetailScreenTest.kt
feature/ruledetail/src/main/kotlin/com/merxury/blocker/feature/ruledetail/RuleDetailScreen.kt
feature/ruledetail/src/main/kotlin/com/merxury/blocker/feature/ruledetail/RuleDetailViewModel.kt
feature/ruledetail/src/test/kotlin/com/merxury/blocker/feature/ruledetail/RuleDetailScreenScreenshotTests.kt

Change-Id: If498e0cfc1b97e530ca0f0a7dd435b9c748024d6

Merge RuleInfoUiState and RuleMatchedAppListUiState

---

feature/appdetail/build.gradle.kts
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailScreen.kt
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailViewModel.kt
feature/applist/build.gradle.kts
feature/applist/src/androidTest/kotlin/com/merxury/blocker/feature/applist/AppListScreenTest.kt
feature/applist/src/main/kotlin/com/merxury/blocker/feature/applist/AppListScreen.kt
feature/applist/src/main/kotlin/com/merxury/blocker/feature/applist/AppListViewModel.kt
feature/applist/src/test/kotlin/com/merxury/blocker/feature/applist/AppListScreenScreenshotTests.kt

---
---
formatting)
Fixes [#401>](https://github.com/lihenggui/blocker/issues/401) 🦕

Pull refresh

---

feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/SettingsViewModel.kt

Change-Id: I7deacf158349b6fe115b30b4669721563c67cde8

Fix #452: Use the correct function for logging errors

---

build-logic/convention/build.gradle.kts
build-logic/convention/src/main/kotlin/com/merxury/blocker/AndroidCompose.kt
gradle/libs.versions.toml

[Experimental]Use Roborazzi outputDir extension

---

feature/applist/src/main/kotlin/com/merxury/blocker/feature/applist/AppListViewModel.kt

Fix #465: Cancel jobs for updating service info before updating the list

---

core/component-controller/src/main/kotlin/com/merxury/blocker/core/controllers/shizuku/ShizukuAppController.kt
core/component-controller/src/main/kotlin/com/merxury/blocker/core/controllers/shizuku/ShizukuController.kt

(cherry picked from commit 6c7a34bbea9f84c9d0820167794ef6a2a51c9438)

Tidy up code style

---

core/component-controller/src/main/java/android/app/ActivityManagerNative.java
core/component-controller/src/main/java/android/app/IActivityManager.java
core/component-controller/src/main/kotlin/com/merxury/blocker/core/controllers/shizuku/ShizukuAppController.kt

(cherry picked from commit 411f477e00ba27e56cd7445ca92741cf0ff6cca9)

Fix IActivityManager on API < 26

---

app-compose/src/main/kotlin/com/merxury/blocker/navigation/BlockerNavHost.kt
app-compose/src/main/kotlin/com/merxury/blocker/ui/BlockerApp.kt
app-compose/src/main/kotlin/com/merxury/blocker/ui/BlockerAppState.kt

---
---
formatting)
Fixes dismiss BottomSheet 🦕

Fix dismiss bottomsheet

---

feature/search/src/main/kotlin/com/merxury/blocker/feature/search/SearchViewModel.kt

---
---
formatting)
Fixes #527 🦕

Fix selection state is not correct

---

feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailViewModel.kt

Change-Id: I8603422904b18e09f558a714244439cc1244209d
The `first()` function only retrieve the data once, it did not receive update events from the `updateComponentList` function. 
Use the `collect` function to receive events from db instead. 
Fixes #569  🦕

Fix #569: Listen to the update events from rooms db

---

core/rule/src/main/kotlin/com/merxury/blocker/core/rule/work/ImportBlockerRuleWorker.kt

Fix #569: Check status before controlling components

---

feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailScreen.kt
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailViewModel.kt

…Screen
---
---
formatting)
Fixes [ #<issue_number_goes_here>](https://github.com/lihenggui/blocker/issues/420) 🦕

Fix the position of focus incorrect in the testField on the AppDetailScreen

---

core/ui/src/main/kotlin/com/merxury/blocker/core/ui/topbar/SelectedAppTopBar.kt
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AnalyticsExtension.kt
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailScreen.kt
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/AppDetailViewModel.kt
feature/appdetail/src/main/kotlin/com/merxury/blocker/feature/appdetail/sdk/SdkContent.kt
feature/search/src/main/kotlin/com/merxury/blocker/feature/search/SearchScreen.kt

Sdk tab: support filter and operations

---

feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/item/BlockerSettings.kt
feature/settings/src/main/res/values-es/strings.xml
feature/settings/src/main/res/values-ru/strings.xml
feature/settings/src/main/res/values-zh-rCN/strings.xml
feature/settings/src/main/res/values-zh-rTW/strings.xml
feature/settings/src/main/res/values/strings.xml
lint.xml

Link to https://github.com/lihenggui/blocker/pull/629

Add French support

---

feature/ruledetail/build.gradle.kts
feature/ruledetail/src/main/kotlin/com/merxury/blocker/feature/ruledetail/component/RuleDescription.kt
gradle/libs.versions.toml

Closes https://github.com/lihenggui/blocker/issues/640

Render markdown contents in the rule description screen

---

.github/workflows/Build.yaml
.github/workflows/Release.yml

Changelog: https://github.com/gradle/gradle-build-action/releases/tag/v3.0.0-rc.1

Use gradle/actions/setup-gradle@v3

---

core/data/src/main/kotlin/com/merxury/blocker/core/data/respository/generalrule/LocalGeneralRuleDataSource.kt

Fix #739: Use decodeFromString for devices running M or older OS.

---

core/ifw-api/src/main/kotlin/com/merxury/core/ifw/IIntentFirewall.kt
core/ifw-api/src/main/kotlin/com/merxury/core/ifw/IntentFirewall.kt
core/ifw-api/src/main/kotlin/com/merxury/core/ifw/di/IfwModule.kt
core/rule/src/main/kotlin/com/merxury/blocker/core/rule/work/ResetIfwWorker.kt

Reset caches when clearing ifw rules

---

feature/search/src/main/kotlin/com/merxury/blocker/feature/search/SearchViewModel.kt

Reset switch status after finishing bulk operations

---

feature/ruledetail/build.gradle.kts
feature/ruledetail/src/main/kotlin/com/merxury/blocker/feature/ruledetail/RuleDetailViewModel.kt
feature/ruledetail/src/test/kotlin/com/merxury/blocker/feature/ruledetail/RuleDetailViewModelTest.kt

RuleDetailViewModelTest

---

build.gradle.kts
generateModuleGraphs.sh

Change-Id: I1f9bf909708a8b787507c2ad78c83c75885fc788

Remove the printModulePaths task and read modules direct from settings

---

feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/SettingsViewModel.kt

Fix #672: Use correct job for importing MAT rules

---

.github/workflows/Build.yaml

Change-Id: Ibc8d6d35520e76ff0711a010653353138dd0dad3

Add steps to update badging automatically

---

feature/settings/src/main/kotlin/com/merxury/blocker/feature/licenses/LicensesScreen.kt
feature/settings/src/main/kotlin/com/merxury/blocker/feature/licenses/LicensesViewModel.kt

Feature/licensee: Move count licenses size into viewModel

---

core/data/src/main/kotlin/com/merxury/blocker/core/data/util/AppPermissionMonitor.kt

Fix #992: Use the right condition to show hint

---

build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
feature/settings/src/main/kotlin/com/merxury/blocker/feature/helpandfeedback/navigation/SupportAndFeedbackNavigation.kt
feature/settings/src/main/kotlin/com/merxury/blocker/feature/licenses/navigation/LicensesNavigation.kt
feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/navigation/SettingsNavigation.kt

Migrate to Type safety navigation

---

app-compose/dependencies/marketReleaseRuntimeClasspath.txt
gradle/libs.versions.toml

Reverts lihenggui/blocker#1155

Revert "Bump androidx.activity:activity-compose from 1.9.3 to 1.10.1"

---

core/ui/src/main/kotlin/com/merxury/blocker/core/ui/collapseList/CollapsibleList.kt
core/ui/src/main/kotlin/com/merxury/blocker/core/ui/component/ComponentListItem.kt

fix-issues

---

.github/workflows/Release.yml

Change-Id: Iac55f228ddbf68cdb1d7bd90fc4dd6bb2d1313f4

Fix changelog writing in Release.yml to use environment variable
